name: GitHub CI
on:
  push:
    paths:
      - '.github/workflows/**'
      - 'Examples/**'
      - 'src/**'
      - '!**/*.md'
    branches:
      - master
  pull_request:
    paths:
      - 'Examples/**'
      - 'src/**'
      - '!**/*.md'
    branches:
      - master
  release:
    types: released

jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build
        shell: pwsh
        run: |
          $msbuildPath = Split-Path (& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\Current\Bin\amd64\MSBuild.exe | Select-Object -First 1) -Parent
          $env:PATH = $msbuildPath + ';' + $env:PATH
          .\build.ps1

      - name: upload-artifact doesn't support wildcards
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        shell: pwsh
        run: |
          New-Item -ItemType Directory nuget_files > $null
          Copy-Item src\bin\Release\*.*nupkg nuget_files

      - uses: actions/upload-artifact@v1
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        with:
          name: nupkg
          path: nuget_files

      - name: Upload to nuget.org
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        run: dotnet nuget push nuget_files\*.nupkg --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

  # Make sure it builds on Linux too
  build-ubuntu:
    name: Build (Ubuntu)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build
        shell: pwsh
        run: ./build.ps1
